version: '3'
services:
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    ports:
      - '80:80'
    volumes:
      - ./app:/var/www/html
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'mvc_project'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
